export const LOGIN = "LOGIN"
export const SIGNUP = "SIGNUP"
export const LOG_OUT = "LOG_OUT"
export const REDUX_LOG_IN = "REDUX_LOG_IN"
export const REDUX_LOG_OUT = "REDUX_LOG_OUT"
export const SHOW_POST = "SHOW_POST"
export const FETCH_ARTICLES = "FETCH_ARTICLES"
export const FETCH_GAMES = "FETCH_GAMES"